version: '3.8'
name: projekt
services:
  client:
    image: "nginx:1.25.3-alpine-slim"
    container_name: web
    ports:
      - "8081:80"
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - network

  dbserver:
    build: ./db
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ita_dbprog
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    networks:
      - network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s

  springserver:
    build: ./appServer
    container_name: appServer
    ports:
      - 8080:8080
    depends_on:
      dbserver:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://dbserver:3306/ita_dbprog
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - network

networks:
  network:
    driver: bridge
